### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by sbalnojan** [meltano/meltano-codespace-ready#7]
@aaronsteers @WillDaSilva I really want to add some kind of test here, won't be fun if this doesn't work.

And that's totally possible as taps and targets are used that I can't really pin to a version (in a nice way that also works with the tut). 

Any ideas on how to best run 1-2 simple tests here?

**Comment by WillDaSilva** [comment]
@edgarrmondragon Can plugin lockfiles be used here to ensure that the same version of the plugins are used each time?

**Comment by sbalnojan** [comment]
https://github.com/meltano/meltano-codespace-ready/pull/9

**Comment by edgarrmondragon** [comment]
@WillDaSilva that'd probably be #6416
